version: 2

jobs:
  check-tf-config:
    working_directory: /tmp/project
    docker:
      - image: circleci/python:3.9.9-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Run Chekhov
          command: |
            sudo pip install -U checkov
            export TF_VERSION=1.1.6
            sudo wget https://releases.hashicorp.com/terraform/"${TF_VERSION}"/terraform_"${TF_VERSION}"_linux_amd64.zip
            sudo apt install zip -y
            sudo unzip terraform_"${TF_VERSION}"_linux_amd64.zip
            sudo mv terraform /usr/local/bin/
            terraform init
            terraform plan -out tf.plan
            terraform show -json tf.plan  > tf.json 
            checkov -f tf.json -s
      - persist_to_workspace:
          root: .
          paths:
            - .

  generate-tf-plan:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  run-tf-apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy
      - persist_to_workspace:
          root: .
          paths:
            - .

  run-tf-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve -auto-approve tfdestroy
            
  
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - check-tf-config
      - plan-approve:
          type: approval
          requires:
            - check-tf-config
      - generate-tf-plan:
          requires:
            - plan-approve
      - hold-apply:
          type: approval
          requires:
            - generate-tf-plan
      - run-tf-apply:
          requires:
            - hold-apply
      - plan-destroy:
          requires:
            - run-tf-apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - run-tf-destroy:
          requires:
            - hold-destroy
      